### ISSUE TITLE
Pants 1.21.0 - Exception message: 'function' object has no attribute 'fget'

### ISSUE THREAD

**Issue by vmorarian** [trueaccord/scalapb-pants#12]
Hi,
It looks like latest pant version is not compatible with scalapb plugin :(
I updated https://github.com/scalapb/scalapb-pants-example

```
$ PANTS_PRINT_EXCEPTION_STACKTRACE=True ./pants run src/scala/example/grpc:client -ldebug

18:34:28 [DEBUG] pants.base.exception_sink:pid=42052: re-enabling faulthandler
18:34:28 [DEBUG] pants.build_graph.build_configuration:pid=42052: Target alias resources has already been registered. Overwriting!
18:34:28 [DEBUG] pants.base.project_tree:pid=42052: ProjectTree ignore_patterns: ['.*/', '/dist/', '/.pants.d', '/dist']
18:34:28 [DEBUG] pants.init.target_roots_calculator:pid=42052: spec_roots are: Specs(dependencies<Exactly(tuple)>=(SingleAddress(directory='src/scala/example/grpc', name='client'),), matcher<Exactly(SpecsMatcher)>=SpecsMatcher(tags<Exactly(tuple)>=(), exclude_patterns<Exactly(tuple)>=()))
18:34:28 [DEBUG] pants.init.target_roots_calculator:pid=42052: changed_request is: ChangedRequest(changes_since=None, diffspec=None, include_dependees=none, fast=False)
18:34:28 [DEBUG] pants.init.target_roots_calculator:pid=42052: owned_files are: []
18:34:29 [DEBUG] pants.base.exception_sink:pid=42052: overriding the global exiter with <pants.bin.local_pants_runner.LocalExiter object at 0x1b91d3e8110> (from <pants.base.exiter.Exiter object at 0x10d7e09d0>)
18:34:29 [DEBUG] pants.init.engine_initializer:pid=42052: target_roots are: TargetRoots(specs=Specs(dependencies=(SingleAddress(directory='src/scala/example/grpc', name='client'),), matcher=SpecsMatcher(tags=(), exclude_patterns=())))
18:34:29 [DEBUG] pants.init.engine_initializer:pid=42052: build_graph is: <pants.engine.legacy.graph.LegacyBuildGraph object at 0x1b91d3e88d0>
18:34:29 [DEBUG] pants.engine.legacy.graph:pid=42052: Injecting specs to <pants.engine.legacy.graph.LegacyBuildGraph object at 0x1b91d3e88d0>: Specs(dependencies<Exactly(tuple)>=(SingleAddress(directory='src/scala/example/grpc', name='client'),), matcher<Exactly(SpecsMatcher)>=SpecsMatcher(tags<Exactly(tuple)>=(), exclude_patterns<Exactly(tuple)>=()))
18:34:29 [DEBUG] engine::scheduler: Launching 1 roots.
18:34:29 [DEBUG] engine::scheduler: Root Select(Specs(dependencies<Exactly(tuple)>=(SingleAddress(directory='src/scala/example/grpc', name='client'),), matcher<Exactly(SpecsMatcher)>=SpecsMatcher(tags<Exactly(tuple)>=(), exclude_patterns<Exactly(tuple)>=())), TransitiveHydratedTargets) completed.
18:34:29 [DEBUG] pants.engine.scheduler:pid=42052: computed 1 nodes in 0.017019 seconds. there are 43 total nodes.
18:34:29 [DEBUG] pants.build_graph.target:pid=42052: src/scala/example/grpc:client ignoring the unimplemented arguments: source = Main.scala
timestamp: 2019-10-24T21:34:29.085434
Exception caught: (builtins.AttributeError)
  File "/Users/vitaliy/.cache/pants/setup/bootstrap-Darwin-x86_64/1.21.0_py37/bin/pants", line 8, in <module>
    sys.exit(main())
  File "/Users/vitaliy/.cache/pants/setup/bootstrap-Darwin-x86_64/1.21.0_py37/lib/python3.7/site-packages/pants/bin/pants_loader.py", line 78, in main
    PantsLoader.run()
  File "/Users/vitaliy/.cache/pants/setup/bootstrap-Darwin-x86_64/1.21.0_py37/lib/python3.7/site-packages/pants/bin/pants_loader.py", line 74, in run
    cls.load_and_execute(entrypoint)
  File "/Users/vitaliy/.cache/pants/setup/bootstrap-Darwin-x86_64/1.21.0_py37/lib/python3.7/site-packages/pants/bin/pants_loader.py", line 67, in load_and_execute
    entrypoint_main()
  File "/Users/vitaliy/.cache/pants/setup/bootstrap-Darwin-x86_64/1.21.0_py37/lib/python3.7/site-packages/pants/bin/pants_exe.py", line 32, in main
    PantsRunner(start_time=start_time).run()
  File "/Users/vitaliy/.cache/pants/setup/bootstrap-Darwin-x86_64/1.21.0_py37/lib/python3.7/site-packages/pants/bin/pants_runner.py", line 99, in run
    return runner.run()
  File "/Users/vitaliy/.cache/pants/setup/bootstrap-Darwin-x86_64/1.21.0_py37/lib/python3.7/site-packages/pants/bin/local_pants_runner.py", line 240, in run
    self._run()
  File "/Users/vitaliy/.cache/pants/setup/bootstrap-Darwin-x86_64/1.21.0_py37/lib/python3.7/site-packages/pants/bin/local_pants_runner.py", line 309, in _run
    goal_runner_result = self._maybe_run_v1()
  File "/Users/vitaliy/.cache/pants/setup/bootstrap-Darwin-x86_64/1.21.0_py37/lib/python3.7/site-packages/pants/bin/local_pants_runner.py", line 268, in _maybe_run_v1
    return goal_runner_factory.create().run()
  File "/Users/vitaliy/.cache/pants/setup/bootstrap-Darwin-x86_64/1.21.0_py37/lib/python3.7/site-packages/pants/bin/goal_runner.py", line 122, in create
    goals, context = self._setup_context()
  File "/Users/vitaliy/.cache/pants/setup/bootstrap-Darwin-x86_64/1.21.0_py37/lib/python3.7/site-packages/pants/bin/goal_runner.py", line 92, in _setup_context
    self._root_dir
  File "/Users/vitaliy/.cache/pants/setup/bootstrap-Darwin-x86_64/1.21.0_py37/lib/python3.7/site-packages/pants/init/engine_initializer.py", line 209, in create_build_graph
    for _ in graph.inject_roots_closure(target_roots):
  File "/Users/vitaliy/.cache/pants/setup/bootstrap-Darwin-x86_64/1.21.0_py37/lib/python3.7/site-packages/pants/engine/legacy/graph.py", line 190, in inject_roots_closure
    for address in self._inject_specs(target_roots.specs):
  File "/Users/vitaliy/.cache/pants/setup/bootstrap-Darwin-x86_64/1.21.0_py37/lib/python3.7/site-packages/pants/engine/legacy/graph.py", line 244, in _inject_specs
    self._index(thts.closure)
  File "/Users/vitaliy/.cache/pants/setup/bootstrap-Darwin-x86_64/1.21.0_py37/lib/python3.7/site-packages/pants/engine/legacy/graph.py", line 109, in _index
    for spec in target.compute_dependency_specs(payload=target.payload):
  File "/Users/vitaliy/.cache/pants/setup/bootstrap-Darwin-x86_64/1.21.0_py37/lib/python3.7/site-packages/pants/build_graph/import_remote_sources_mixin.py", line 109, in compute_dependency_specs
    imported_target_specs = cls.imported_target_specs(kwargs=kwargs, payload=payload)
  File "/Users/vitaliy/.cache/pants/setup/bootstrap-Darwin-x86_64/1.21.0_py37/lib/python3.7/site-packages/pants/build_graph/import_remote_sources_mixin.py", line 66, in imported_target_specs
    field = cls.imported_target_payload_field
  File "/Users/vitaliy/.cache/pants/setup/bootstrap-Darwin-x86_64/1.21.0_py37/lib/python3.7/site-packages/pants/util/meta.py", line 33, in __get__
    field_name = self.fget.__func__.fget.__name__

Exception message: 'function' object has no attribute 'fget'
```

**Comment by thesamet** [comment]
Hi @vmorarian and thanks for reporting this issue! The exception doesn't mention ScalaPB - are you sure it is related? Also, will you be able to work on a PR to fix this?

**Comment by vmorarian** [comment]
@thesamet yes, because project without protobuf/grpc stuff compiles without any issues

as I mentioned, it throws exception .. but it's expectable case (however in this case it can't call `fget` method)
https://github.com/pantsbuild/pants/blob/master/src/python/pants/util/meta.py#L47-L54

so I added few `print` statements
```
...
    if getattr(self.fget.__func__, '__isabstractmethod__', False):
      print(">>>")
      print(objtype)
      print(self.fget.__func__.__name__)
      field_name = self.fget.__func__.fget.__name__
...
```
and got
```
>>>
<class 'trueaccord.pants.scalapb.targets.scalapb_library.ScalaPBLibrary'>
imported_target_payload_field
```

I'm not familiar with pants internals, but it looks like `ScalaPBLibrary` should contain additional method
```
 @property
 def imported_target_payload_field(self):
   return ???????
```

**Comment by vmorarian** [comment]
@thesamet any ideas?

**Comment by thesamet** [comment]
Released v0.4.0 with a fix. I also renamed the module from `trueaccord.pants.scalapb` to `scalapb.pants`. After upgrading to 0.4.0,

change `pants.ini` to have:
```
 backend_packages: +[
  'scalapb.pants'
   ]
```

**Comment by vmorarian** [comment]
@thesamet cool! Thank you! 👍

**Comment by thesamet** [comment]
I believe this has been resolved.
